# Generated by Django 2.2.3 on 2019-07-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20180331_1945'),
        ('customers', '0002_customers'),
    ]

    operations = [
    ]
